<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>块作用域 on sugar的读书笔记</title>
    <link>http://hongliya.me/tags/%E5%9D%97%E4%BD%9C%E7%94%A8%E5%9F%9F/</link>
    <description>Recent content in 块作用域 on sugar的读书笔记</description>
    <generator>Hugo -- gohugo.io</generator>
    <language>en-us</language>
    <lastBuildDate>Wed, 11 Oct 2017 00:00:00 +0000</lastBuildDate>
    
	<atom:link href="http://hongliya.me/tags/%E5%9D%97%E4%BD%9C%E7%94%A8%E5%9F%9F/index.xml" rel="self" type="application/rss+xml" />
    
    
    <item>
      <title>JavaScript：块作用域</title>
      <link>http://hongliya.me/post/javascript_block_scope/</link>
      <pubDate>Wed, 11 Oct 2017 00:00:00 +0000</pubDate>
      
      <guid>http://hongliya.me/post/javascript_block_scope/</guid>
      <description>读书笔记《你不知道的JavaScript（上卷）》块作用域。
表面上看 JavaScript 并没有块作用域的相关功能，其实有。
 with try/catch let  with with会创建一个新的作用域（块作用域），但不推荐使用，不说了。
try/catch ES3规范中规定的try/catch的catch分句会创建一个新的作用域（块作用域），其中声明的变量仅在catch内部有效。
实例分析 try { undefined(); } catch(err) { console.log(err); // TypeError: undefined is not a function } console.log(err); // ReferenceError: err is not defined  栈分析：
第一步：undefined()函数不存在，进入catch作用域，执行完后销毁。
 console作用域   输出结果 &#39;TypeError: undefined is not a function&#39;    catch作用域   调用console.log(err) err = &#39;TypeError: undefined is not a function&#39;    全局作用域   调用undefined()      第一步：调用console.</description>
    </item>
    
  </channel>
</rss>